#!python3
import requests
res = requests.get('https://www.gutenburg.org/cache/epub/1112/pg1112.text')
type(res)
res.status_code == requests.codes.ok
len(res.text)
print(res.text[:250])
res1 = requests.get('https://inventwithpython.com/page_that_does_not_exist')
try:
    res.raise_for_status()
except Exception as exc:
    print("There was a problem: $s" % (exc))
