# coding: utf-8
series1 = np.array([3,4,5,3])
series2 = np.array([1,2,2,5])
series3 = np.array([2,3,3,4])
index = np.arange(4)
plt.axis([-0.5, 3.5, 0, 15])
plt.title("A multiseries Stacked Bar Chart")
plt.bar(index, series1, color='r')
plt.bar(index, series2, color='b', bottom=series1)
plt.bar(index, series3, color='g', bottom=(series2+series1))
plt.xticks(index+0.4, ['Jan18', 'Feb18', 'Mar18', 'Apr18'])
plt.show()
